// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	CustomerID           int32    `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	InternalCustomerID   string   `protobuf:"bytes,3,opt,name=InternalCustomerID,proto3" json:"InternalCustomerID,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	RowVersion           string   `protobuf:"bytes,6,opt,name=RowVersion,proto3" json:"RowVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetInternalCustomerID() string {
	if m != nil {
		return m.InternalCustomerID
	}
	return ""
}

func (m *Customer) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Customer) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Customer) GetRowVersion() string {
	if m != nil {
		return m.RowVersion
	}
	return ""
}

type CustomerCredentials struct {
	ClientAPIKey         string   `protobuf:"bytes,1,opt,name=ClientAPIKey,proto3" json:"ClientAPIKey,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	CustomerID           int32    `protobuf:"varint,3,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerCredentials) Reset()         { *m = CustomerCredentials{} }
func (m *CustomerCredentials) String() string { return proto.CompactTextString(m) }
func (*CustomerCredentials) ProtoMessage()    {}
func (*CustomerCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *CustomerCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerCredentials.Unmarshal(m, b)
}
func (m *CustomerCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerCredentials.Marshal(b, m, deterministic)
}
func (m *CustomerCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerCredentials.Merge(m, src)
}
func (m *CustomerCredentials) XXX_Size() int {
	return xxx_messageInfo_CustomerCredentials.Size(m)
}
func (m *CustomerCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerCredentials proto.InternalMessageInfo

func (m *CustomerCredentials) GetClientAPIKey() string {
	if m != nil {
		return m.ClientAPIKey
	}
	return ""
}

func (m *CustomerCredentials) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CustomerCredentials) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CustomerCredentials) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CustomerCredentials) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type CustomerIP struct {
	CustomerIP           string   `protobuf:"bytes,1,opt,name=CustomerIP,proto3" json:"CustomerIP,omitempty"`
	CustomerID           int32    `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerIP) Reset()         { *m = CustomerIP{} }
func (m *CustomerIP) String() string { return proto.CompactTextString(m) }
func (*CustomerIP) ProtoMessage()    {}
func (*CustomerIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *CustomerIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerIP.Unmarshal(m, b)
}
func (m *CustomerIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerIP.Marshal(b, m, deterministic)
}
func (m *CustomerIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerIP.Merge(m, src)
}
func (m *CustomerIP) XXX_Size() int {
	return xxx_messageInfo_CustomerIP.Size(m)
}
func (m *CustomerIP) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerIP.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerIP proto.InternalMessageInfo

func (m *CustomerIP) GetCustomerIP() string {
	if m != nil {
		return m.CustomerIP
	}
	return ""
}

func (m *CustomerIP) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CustomerIP) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CustomerIP) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type CustomerProduct struct {
	CustomerProductID    int32    `protobuf:"varint,1,opt,name=CustomerProductID,proto3" json:"CustomerProductID,omitempty"`
	CustomerProduct      string   `protobuf:"bytes,2,opt,name=CustomerProduct,proto3" json:"CustomerProduct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerProduct) Reset()         { *m = CustomerProduct{} }
func (m *CustomerProduct) String() string { return proto.CompactTextString(m) }
func (*CustomerProduct) ProtoMessage()    {}
func (*CustomerProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{3}
}

func (m *CustomerProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerProduct.Unmarshal(m, b)
}
func (m *CustomerProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerProduct.Marshal(b, m, deterministic)
}
func (m *CustomerProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerProduct.Merge(m, src)
}
func (m *CustomerProduct) XXX_Size() int {
	return xxx_messageInfo_CustomerProduct.Size(m)
}
func (m *CustomerProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerProduct.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerProduct proto.InternalMessageInfo

func (m *CustomerProduct) GetCustomerProductID() int32 {
	if m != nil {
		return m.CustomerProductID
	}
	return 0
}

func (m *CustomerProduct) GetCustomerProduct() string {
	if m != nil {
		return m.CustomerProduct
	}
	return ""
}

type CustomerServiceOfferings struct {
	CustomerID                int32    `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	CustomerServiceOfferingID int32    `protobuf:"varint,2,opt,name=CustomerServiceOfferingID,proto3" json:"CustomerServiceOfferingID,omitempty"`
	CustomerClientProductID   int32    `protobuf:"varint,3,opt,name=CustomerClientProductID,proto3" json:"CustomerClientProductID,omitempty"`
	StartDate                 string   `protobuf:"bytes,4,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate                   string   `protobuf:"bytes,5,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	BillingCycle              string   `protobuf:"bytes,6,opt,name=BillingCycle,proto3" json:"BillingCycle,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *CustomerServiceOfferings) Reset()         { *m = CustomerServiceOfferings{} }
func (m *CustomerServiceOfferings) String() string { return proto.CompactTextString(m) }
func (*CustomerServiceOfferings) ProtoMessage()    {}
func (*CustomerServiceOfferings) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{4}
}

func (m *CustomerServiceOfferings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerServiceOfferings.Unmarshal(m, b)
}
func (m *CustomerServiceOfferings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerServiceOfferings.Marshal(b, m, deterministic)
}
func (m *CustomerServiceOfferings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerServiceOfferings.Merge(m, src)
}
func (m *CustomerServiceOfferings) XXX_Size() int {
	return xxx_messageInfo_CustomerServiceOfferings.Size(m)
}
func (m *CustomerServiceOfferings) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerServiceOfferings.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerServiceOfferings proto.InternalMessageInfo

func (m *CustomerServiceOfferings) GetCustomerID() int32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CustomerServiceOfferings) GetCustomerServiceOfferingID() int32 {
	if m != nil {
		return m.CustomerServiceOfferingID
	}
	return 0
}

func (m *CustomerServiceOfferings) GetCustomerClientProductID() int32 {
	if m != nil {
		return m.CustomerClientProductID
	}
	return 0
}

func (m *CustomerServiceOfferings) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CustomerServiceOfferings) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *CustomerServiceOfferings) GetBillingCycle() string {
	if m != nil {
		return m.BillingCycle
	}
	return ""
}

func init() {
	proto.RegisterType((*Customer)(nil), "models.Customer")
	proto.RegisterType((*CustomerCredentials)(nil), "models.CustomerCredentials")
	proto.RegisterType((*CustomerIP)(nil), "models.CustomerIP")
	proto.RegisterType((*CustomerProduct)(nil), "models.CustomerProduct")
	proto.RegisterType((*CustomerServiceOfferings)(nil), "models.CustomerServiceOfferings")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0x65, 0xfb, 0x67, 0x7f, 0xbf, 0x0e, 0x45, 0x71, 0x04, 0x5d, 0x41, 0xa4, 0xe4, 0xd4, 0x83,
	0xf4, 0xe2, 0xc5, 0x83, 0x17, 0xdd, 0x7a, 0x28, 0x82, 0x2e, 0x5b, 0xf0, 0xbe, 0xee, 0x4e, 0x4b,
	0x20, 0x4d, 0x24, 0x9b, 0x2a, 0xbd, 0x7b, 0xf6, 0x7b, 0xf8, 0x45, 0xfc, 0x5c, 0x62, 0xcc, 0xb6,
	0xbb, 0xad, 0x5b, 0xa1, 0xb7, 0xe4, 0xbd, 0xc9, 0xe4, 0xcd, 0xcb, 0x0b, 0xec, 0xa5, 0xf3, 0xdc,
	0xa8, 0x19, 0xe9, 0xc1, 0xb3, 0x56, 0x46, 0xa1, 0x3f, 0x53, 0x19, 0x89, 0x9c, 0x7d, 0x7a, 0xf0,
	0x3f, 0x74, 0x14, 0x9e, 0x01, 0x14, 0xeb, 0xd1, 0x30, 0xf0, 0x7a, 0x5e, 0xbf, 0x1d, 0x97, 0x10,
	0x44, 0x68, 0xdd, 0x27, 0x33, 0x0a, 0x1a, 0x3d, 0xaf, 0xdf, 0x89, 0xed, 0x1a, 0x07, 0x80, 0x23,
	0x69, 0x48, 0xcb, 0x44, 0x94, 0xce, 0x36, 0x6d, 0xc5, 0x2f, 0x0c, 0x9e, 0x42, 0x67, 0x6c, 0x12,
	0x6d, 0x86, 0x89, 0xa1, 0xa0, 0x65, 0xcb, 0x56, 0x00, 0x06, 0xf0, 0xef, 0x56, 0x66, 0x96, 0x6b,
	0x5b, 0xae, 0xd8, 0x7e, 0x6b, 0x8b, 0xd5, 0xeb, 0x23, 0xe9, 0x9c, 0x2b, 0x19, 0xf8, 0x96, 0x2c,
	0x21, 0xec, 0xc3, 0x83, 0xc3, 0xe2, 0x9a, 0x50, 0x53, 0x46, 0xd2, 0xf0, 0x44, 0xe4, 0xc8, 0xa0,
	0x1b, 0x0a, 0x4e, 0xd2, 0x5c, 0x47, 0xa3, 0x3b, 0x5a, 0xd8, 0xa9, 0x3a, 0x71, 0x05, 0xc3, 0x23,
	0xf0, 0xc7, 0x94, 0x6a, 0x32, 0x6e, 0x32, 0xb7, 0x5b, 0xf3, 0xa3, 0xb9, 0xe1, 0xc7, 0x8e, 0xb3,
	0xb0, 0x37, 0xaf, 0xd4, 0x38, 0xaa, 0x5c, 0x13, 0x39, 0x81, 0x75, 0xfc, 0xd0, 0x4a, 0xdc, 0x22,
	0xa3, 0xb9, 0x45, 0x46, 0xab, 0x2a, 0x83, 0xc3, 0x7e, 0xd1, 0x25, 0xd2, 0x2a, 0x9b, 0xa7, 0x06,
	0xcf, 0xe1, 0x60, 0x0d, 0x5a, 0x06, 0x61, 0x93, 0xc0, 0xfe, 0x46, 0x03, 0x67, 0xe0, 0x3a, 0xcc,
	0xde, 0x1b, 0x10, 0x14, 0xd8, 0x98, 0xf4, 0x0b, 0x4f, 0xe9, 0x61, 0x32, 0x21, 0xcd, 0xe5, 0x34,
	0xff, 0x33, 0x76, 0x57, 0x70, 0x52, 0x73, 0x76, 0x69, 0x47, 0x7d, 0x01, 0x5e, 0xc2, 0xf1, 0x32,
	0x17, 0xf6, 0xd1, 0x57, 0x83, 0xfd, 0xbc, 0x68, 0x1d, 0xbd, 0x73, 0x54, 0x19, 0x74, 0x6f, 0xb8,
	0x10, 0x5c, 0x4e, 0xc3, 0x45, 0x2a, 0xc8, 0x85, 0xb5, 0x82, 0x3d, 0xf9, 0xf6, 0x1b, 0x5e, 0x7c,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xb1, 0x29, 0xa1, 0x98, 0x03, 0x00, 0x00,
}
