// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.9.0
// source: expMatch.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PatronName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  string `protobuf:"bytes,1,opt,name=First,proto3" json:"First,omitempty"`
	Last   string `protobuf:"bytes,2,opt,name=Last,proto3" json:"Last,omitempty"`
	Middle string `protobuf:"bytes,3,opt,name=Middle,proto3" json:"Middle,omitempty"`
	Gen    string `protobuf:"bytes,4,opt,name=Gen,proto3" json:"Gen,omitempty"`
}

func (x *PatronName) Reset() {
	*x = PatronName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expMatch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatronName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatronName) ProtoMessage() {}

func (x *PatronName) ProtoReflect() protoreflect.Message {
	mi := &file_expMatch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatronName.ProtoReflect.Descriptor instead.
func (*PatronName) Descriptor() ([]byte, []int) {
	return file_expMatch_proto_rawDescGZIP(), []int{0}
}

func (x *PatronName) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *PatronName) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *PatronName) GetMiddle() string {
	if x != nil {
		return x.Middle
	}
	return ""
}

func (x *PatronName) GetGen() string {
	if x != nil {
		return x.Gen
	}
	return ""
}

type PatronAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Street string `protobuf:"bytes,1,opt,name=Street,proto3" json:"Street,omitempty"`
	City   string `protobuf:"bytes,2,opt,name=City,proto3" json:"City,omitempty"`
	State  string `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Zip    string `protobuf:"bytes,4,opt,name=Zip,proto3" json:"Zip,omitempty"`
}

func (x *PatronAddress) Reset() {
	*x = PatronAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expMatch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatronAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatronAddress) ProtoMessage() {}

func (x *PatronAddress) ProtoReflect() protoreflect.Message {
	mi := &file_expMatch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatronAddress.ProtoReflect.Descriptor instead.
func (*PatronAddress) Descriptor() ([]byte, []int) {
	return file_expMatch_proto_rawDescGZIP(), []int{1}
}

func (x *PatronAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *PatronAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PatronAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PatronAddress) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type PatronDriversLicense struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  string `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *PatronDriversLicense) Reset() {
	*x = PatronDriversLicense{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expMatch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatronDriversLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatronDriversLicense) ProtoMessage() {}

func (x *PatronDriversLicense) ProtoReflect() protoreflect.Message {
	mi := &file_expMatch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatronDriversLicense.ProtoReflect.Descriptor instead.
func (*PatronDriversLicense) Descriptor() ([]byte, []int) {
	return file_expMatch_proto_rawDescGZIP(), []int{2}
}

func (x *PatronDriversLicense) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PatronDriversLicense) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type Patron struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           *PatronName           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Address        *PatronAddress        `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	DriversLicense *PatronDriversLicense `protobuf:"bytes,3,opt,name=DriversLicense,proto3" json:"DriversLicense,omitempty"`
	Dob            string                `protobuf:"bytes,4,opt,name=Dob,proto3" json:"Dob,omitempty"`
	Phone          string                `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Product        string                `protobuf:"bytes,6,opt,name=Product,proto3" json:"Product,omitempty"`
	TIN            string                `protobuf:"bytes,7,opt,name=TIN,proto3" json:"TIN,omitempty"`
}

func (x *Patron) Reset() {
	*x = Patron{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expMatch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patron) ProtoMessage() {}

func (x *Patron) ProtoReflect() protoreflect.Message {
	mi := &file_expMatch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patron.ProtoReflect.Descriptor instead.
func (*Patron) Descriptor() ([]byte, []int) {
	return file_expMatch_proto_rawDescGZIP(), []int{3}
}

func (x *Patron) GetName() *PatronName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Patron) GetAddress() *PatronAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Patron) GetDriversLicense() *PatronDriversLicense {
	if x != nil {
		return x.DriversLicense
	}
	return nil
}

func (x *Patron) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *Patron) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Patron) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Patron) GetTIN() string {
	if x != nil {
		return x.TIN
	}
	return ""
}

var File_expMatch_proto protoreflect.FileDescriptor

var file_expMatch_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x78, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x60, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x72,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x61, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x65, 0x6e, 0x22, 0x63, 0x0a, 0x0d, 0x50, 0x61,
	0x74, 0x72, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72,
	0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x5a, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x5a, 0x69, 0x70, 0x22,
	0x44, 0x0a, 0x14, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xfb, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x0e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x6f,
	0x6e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x52,
	0x0e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x44, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x6f,
	0x62, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x49, 0x4e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x54, 0x49, 0x4e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_expMatch_proto_rawDescOnce sync.Once
	file_expMatch_proto_rawDescData = file_expMatch_proto_rawDesc
)

func file_expMatch_proto_rawDescGZIP() []byte {
	file_expMatch_proto_rawDescOnce.Do(func() {
		file_expMatch_proto_rawDescData = protoimpl.X.CompressGZIP(file_expMatch_proto_rawDescData)
	})
	return file_expMatch_proto_rawDescData
}

var file_expMatch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_expMatch_proto_goTypes = []interface{}{
	(*PatronName)(nil),           // 0: models.PatronName
	(*PatronAddress)(nil),        // 1: models.PatronAddress
	(*PatronDriversLicense)(nil), // 2: models.PatronDriversLicense
	(*Patron)(nil),               // 3: models.Patron
}
var file_expMatch_proto_depIdxs = []int32{
	0, // 0: models.Patron.Name:type_name -> models.PatronName
	1, // 1: models.Patron.Address:type_name -> models.PatronAddress
	2, // 2: models.Patron.DriversLicense:type_name -> models.PatronDriversLicense
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_expMatch_proto_init() }
func file_expMatch_proto_init() {
	if File_expMatch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expMatch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatronName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expMatch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatronAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expMatch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatronDriversLicense); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expMatch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patron); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expMatch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expMatch_proto_goTypes,
		DependencyIndexes: file_expMatch_proto_depIdxs,
		MessageInfos:      file_expMatch_proto_msgTypes,
	}.Build()
	File_expMatch_proto = out.File
	file_expMatch_proto_rawDesc = nil
	file_expMatch_proto_goTypes = nil
	file_expMatch_proto_depIdxs = nil
}
