// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceOfferings.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceOfferings struct {
	ServiceOfferingID       int32    `protobuf:"varint,1,opt,name=ServiceOfferingID,proto3" json:"ServiceOfferingID,omitempty"`
	Name                    string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ServiceDescription      string   `protobuf:"bytes,3,opt,name=ServiceDescription,proto3" json:"ServiceDescription,omitempty"`
	InternalServiceRecordID string   `protobuf:"bytes,4,opt,name=InternalServiceRecordID,proto3" json:"InternalServiceRecordID,omitempty"`
	StartDate               string   `protobuf:"bytes,5,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate                 string   `protobuf:"bytes,6,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ServiceOfferings) Reset()         { *m = ServiceOfferings{} }
func (m *ServiceOfferings) String() string { return proto.CompactTextString(m) }
func (*ServiceOfferings) ProtoMessage()    {}
func (*ServiceOfferings) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3df0c32531ebe09, []int{0}
}

func (m *ServiceOfferings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOfferings.Unmarshal(m, b)
}
func (m *ServiceOfferings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOfferings.Marshal(b, m, deterministic)
}
func (m *ServiceOfferings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOfferings.Merge(m, src)
}
func (m *ServiceOfferings) XXX_Size() int {
	return xxx_messageInfo_ServiceOfferings.Size(m)
}
func (m *ServiceOfferings) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOfferings.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOfferings proto.InternalMessageInfo

func (m *ServiceOfferings) GetServiceOfferingID() int32 {
	if m != nil {
		return m.ServiceOfferingID
	}
	return 0
}

func (m *ServiceOfferings) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceOfferings) GetServiceDescription() string {
	if m != nil {
		return m.ServiceDescription
	}
	return ""
}

func (m *ServiceOfferings) GetInternalServiceRecordID() string {
	if m != nil {
		return m.InternalServiceRecordID
	}
	return ""
}

func (m *ServiceOfferings) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *ServiceOfferings) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceOfferings)(nil), "models.ServiceOfferings")
}

func init() { proto.RegisterFile("serviceOfferings.proto", fileDescriptor_c3df0c32531ebe09) }

var fileDescriptor_c3df0c32531ebe09 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xf5, 0x4f, 0x4b, 0x4b, 0x2d, 0xca, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0xfa, 0xc6, 0xc8, 0x25, 0x10,
	0x8c, 0xa6, 0x44, 0x48, 0x87, 0x4b, 0x10, 0x4d, 0xcc, 0xd3, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x35, 0x08, 0x53, 0x42, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x16, 0xd2, 0xe3, 0x12, 0x82, 0x2a, 0x74, 0x49, 0x2d, 0x4e, 0x2e, 0xca,
	0x2c, 0x28, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x06, 0xab, 0xc0, 0x22, 0x23, 0x64, 0xc1, 0x25, 0xee,
	0x99, 0x57, 0x92, 0x5a, 0x94, 0x97, 0x98, 0x03, 0x95, 0x0d, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0xf1,
	0x74, 0x91, 0x60, 0x01, 0x6b, 0xc2, 0x25, 0x2d, 0x24, 0xc3, 0xc5, 0x19, 0x5c, 0x92, 0x58, 0x54,
	0xe2, 0x92, 0x58, 0x92, 0x2a, 0xc1, 0x0a, 0x56, 0x8b, 0x10, 0x10, 0x92, 0xe0, 0x62, 0x77, 0xcd,
	0x4b, 0x01, 0xcb, 0xb1, 0x81, 0xe5, 0x60, 0xdc, 0x24, 0x36, 0x70, 0x38, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x2e, 0xe5, 0xee, 0x8b, 0x21, 0x01, 0x00, 0x00,
}
